// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImageModel.proto

package io.fathom.cloud.protobuf;

public final class ImageModel {
  private ImageModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code fathomcloud.protobuf.ImageState}
   */
  public enum ImageState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>QUEUED = 1;</code>
     *
     * <pre>
     * The image identifier has been reserved for an image in the Glance registry. No image data has been uploaded to Glance and the image size was not explicitly set to zero on creation.
     * </pre>
     */
    QUEUED(0, 1),
    /**
     * <code>SAVING = 2;</code>
     *
     * <pre>
     * Denotes that an image’s raw data is currently being uploaded to Glance. When an image is registered with a call to POST /images and there is an x-image-meta-location header present, that image will never be in the saving status (as the image data is already available in some other location).
     * </pre>
     */
    SAVING(1, 2),
    /**
     * <code>ACTIVE = 3;</code>
     *
     * <pre>
     * Denotes an image that is fully available in Glance. This occurs when the image data is uploaded, or the image size is explicitly set to zero on creation.
     * </pre>
     */
    ACTIVE(2, 3),
    /**
     * <code>KILLED = 4;</code>
     *
     * <pre>
     * Denotes that an error occurred during the uploading of an image’s data, and that the image is not readable.
     * </pre>
     */
    KILLED(3, 4),
    /**
     * <code>DELETED = 5;</code>
     *
     * <pre>
     *Glance has retained the information about the image, but it is no longer available to use. An image in this state will be removed automatically at a later date.
     * </pre>
     */
    DELETED(4, 5),
    /**
     * <code>PENDING_DELETE = 6;</code>
     *
     * <pre>
     *This is similiar to deleted, however, Glance has not yet removed the image data. An image in this state is recoverable.
     * </pre>
     */
    PENDING_DELETE(5, 6),
    ;

    /**
     * <code>QUEUED = 1;</code>
     *
     * <pre>
     * The image identifier has been reserved for an image in the Glance registry. No image data has been uploaded to Glance and the image size was not explicitly set to zero on creation.
     * </pre>
     */
    public static final int QUEUED_VALUE = 1;
    /**
     * <code>SAVING = 2;</code>
     *
     * <pre>
     * Denotes that an image’s raw data is currently being uploaded to Glance. When an image is registered with a call to POST /images and there is an x-image-meta-location header present, that image will never be in the saving status (as the image data is already available in some other location).
     * </pre>
     */
    public static final int SAVING_VALUE = 2;
    /**
     * <code>ACTIVE = 3;</code>
     *
     * <pre>
     * Denotes an image that is fully available in Glance. This occurs when the image data is uploaded, or the image size is explicitly set to zero on creation.
     * </pre>
     */
    public static final int ACTIVE_VALUE = 3;
    /**
     * <code>KILLED = 4;</code>
     *
     * <pre>
     * Denotes that an error occurred during the uploading of an image’s data, and that the image is not readable.
     * </pre>
     */
    public static final int KILLED_VALUE = 4;
    /**
     * <code>DELETED = 5;</code>
     *
     * <pre>
     *Glance has retained the information about the image, but it is no longer available to use. An image in this state will be removed automatically at a later date.
     * </pre>
     */
    public static final int DELETED_VALUE = 5;
    /**
     * <code>PENDING_DELETE = 6;</code>
     *
     * <pre>
     *This is similiar to deleted, however, Glance has not yet removed the image data. An image in this state is recoverable.
     * </pre>
     */
    public static final int PENDING_DELETE_VALUE = 6;


    public final int getNumber() { return value; }

    public static ImageState valueOf(int value) {
      switch (value) {
        case 1: return QUEUED;
        case 2: return SAVING;
        case 3: return ACTIVE;
        case 4: return KILLED;
        case 5: return DELETED;
        case 6: return PENDING_DELETE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ImageState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ImageState>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ImageState>() {
            public ImageState findValueByNumber(int number) {
              return ImageState.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.fathom.cloud.protobuf.ImageModel.getDescriptor().getEnumTypes().get(0);
    }

    private static final ImageState[] VALUES = values();

    public static ImageState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ImageState(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:fathomcloud.protobuf.ImageState)
  }

  public interface ImageLocationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string stored = 1;
    /**
     * <code>optional string stored = 1;</code>
     */
    boolean hasStored();
    /**
     * <code>optional string stored = 1;</code>
     */
    java.lang.String getStored();
    /**
     * <code>optional string stored = 1;</code>
     */
    com.google.protobuf.ByteString
        getStoredBytes();
  }
  /**
   * Protobuf type {@code fathomcloud.protobuf.ImageLocation}
   */
  public static final class ImageLocation extends
      com.google.protobuf.GeneratedMessage
      implements ImageLocationOrBuilder {
    // Use ImageLocation.newBuilder() to construct.
    private ImageLocation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ImageLocation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ImageLocation defaultInstance;
    public static ImageLocation getDefaultInstance() {
      return defaultInstance;
    }

    public ImageLocation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ImageLocation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              stored_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.fathom.cloud.protobuf.ImageModel.internal_static_fathomcloud_protobuf_ImageLocation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.fathom.cloud.protobuf.ImageModel.internal_static_fathomcloud_protobuf_ImageLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.fathom.cloud.protobuf.ImageModel.ImageLocation.class, io.fathom.cloud.protobuf.ImageModel.ImageLocation.Builder.class);
    }

    public static com.google.protobuf.Parser<ImageLocation> PARSER =
        new com.google.protobuf.AbstractParser<ImageLocation>() {
      public ImageLocation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImageLocation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ImageLocation> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string stored = 1;
    public static final int STORED_FIELD_NUMBER = 1;
    private java.lang.Object stored_;
    /**
     * <code>optional string stored = 1;</code>
     */
    public boolean hasStored() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string stored = 1;</code>
     */
    public java.lang.String getStored() {
      java.lang.Object ref = stored_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stored_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stored = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStoredBytes() {
      java.lang.Object ref = stored_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stored_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      stored_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStoredBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStoredBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.fathom.cloud.protobuf.ImageModel.ImageLocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageLocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageLocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageLocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageLocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageLocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageLocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageLocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageLocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageLocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.fathom.cloud.protobuf.ImageModel.ImageLocation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fathomcloud.protobuf.ImageLocation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements io.fathom.cloud.protobuf.ImageModel.ImageLocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.fathom.cloud.protobuf.ImageModel.internal_static_fathomcloud_protobuf_ImageLocation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.fathom.cloud.protobuf.ImageModel.internal_static_fathomcloud_protobuf_ImageLocation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.fathom.cloud.protobuf.ImageModel.ImageLocation.class, io.fathom.cloud.protobuf.ImageModel.ImageLocation.Builder.class);
      }

      // Construct using io.fathom.cloud.protobuf.ImageModel.ImageLocation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stored_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.fathom.cloud.protobuf.ImageModel.internal_static_fathomcloud_protobuf_ImageLocation_descriptor;
      }

      public io.fathom.cloud.protobuf.ImageModel.ImageLocation getDefaultInstanceForType() {
        return io.fathom.cloud.protobuf.ImageModel.ImageLocation.getDefaultInstance();
      }

      public io.fathom.cloud.protobuf.ImageModel.ImageLocation build() {
        io.fathom.cloud.protobuf.ImageModel.ImageLocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.fathom.cloud.protobuf.ImageModel.ImageLocation buildPartial() {
        io.fathom.cloud.protobuf.ImageModel.ImageLocation result = new io.fathom.cloud.protobuf.ImageModel.ImageLocation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stored_ = stored_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.fathom.cloud.protobuf.ImageModel.ImageLocation) {
          return mergeFrom((io.fathom.cloud.protobuf.ImageModel.ImageLocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.fathom.cloud.protobuf.ImageModel.ImageLocation other) {
        if (other == io.fathom.cloud.protobuf.ImageModel.ImageLocation.getDefaultInstance()) return this;
        if (other.hasStored()) {
          bitField0_ |= 0x00000001;
          stored_ = other.stored_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.fathom.cloud.protobuf.ImageModel.ImageLocation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.fathom.cloud.protobuf.ImageModel.ImageLocation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string stored = 1;
      private java.lang.Object stored_ = "";
      /**
       * <code>optional string stored = 1;</code>
       */
      public boolean hasStored() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string stored = 1;</code>
       */
      public java.lang.String getStored() {
        java.lang.Object ref = stored_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          stored_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stored = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStoredBytes() {
        java.lang.Object ref = stored_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stored_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stored = 1;</code>
       */
      public Builder setStored(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stored_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stored = 1;</code>
       */
      public Builder clearStored() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stored_ = getDefaultInstance().getStored();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stored = 1;</code>
       */
      public Builder setStoredBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stored_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:fathomcloud.protobuf.ImageLocation)
    }

    static {
      defaultInstance = new ImageLocation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:fathomcloud.protobuf.ImageLocation)
  }

  public interface ImageDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 id = 1;
    /**
     * <code>optional int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    // optional bool is_public = 2;
    /**
     * <code>optional bool is_public = 2;</code>
     */
    boolean hasIsPublic();
    /**
     * <code>optional bool is_public = 2;</code>
     */
    boolean getIsPublic();

    // optional string name = 3;
    /**
     * <code>optional string name = 3;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string disk_format = 4;
    /**
     * <code>optional string disk_format = 4;</code>
     */
    boolean hasDiskFormat();
    /**
     * <code>optional string disk_format = 4;</code>
     */
    java.lang.String getDiskFormat();
    /**
     * <code>optional string disk_format = 4;</code>
     */
    com.google.protobuf.ByteString
        getDiskFormatBytes();

    // optional string container_format = 5;
    /**
     * <code>optional string container_format = 5;</code>
     */
    boolean hasContainerFormat();
    /**
     * <code>optional string container_format = 5;</code>
     */
    java.lang.String getContainerFormat();
    /**
     * <code>optional string container_format = 5;</code>
     */
    com.google.protobuf.ByteString
        getContainerFormatBytes();

    // repeated string tag = 6;
    /**
     * <code>repeated string tag = 6;</code>
     */
    java.util.List<java.lang.String>
    getTagList();
    /**
     * <code>repeated string tag = 6;</code>
     */
    int getTagCount();
    /**
     * <code>repeated string tag = 6;</code>
     */
    java.lang.String getTag(int index);
    /**
     * <code>repeated string tag = 6;</code>
     */
    com.google.protobuf.ByteString
        getTagBytes(int index);

    // optional .fathomcloud.protobuf.ImageLocation location = 7;
    /**
     * <code>optional .fathomcloud.protobuf.ImageLocation location = 7;</code>
     */
    boolean hasLocation();
    /**
     * <code>optional .fathomcloud.protobuf.ImageLocation location = 7;</code>
     */
    io.fathom.cloud.protobuf.ImageModel.ImageLocation getLocation();
    /**
     * <code>optional .fathomcloud.protobuf.ImageLocation location = 7;</code>
     */
    io.fathom.cloud.protobuf.ImageModel.ImageLocationOrBuilder getLocationOrBuilder();

    // optional .fathomcloud.protobuf.ImageState image_state = 8;
    /**
     * <code>optional .fathomcloud.protobuf.ImageState image_state = 8;</code>
     */
    boolean hasImageState();
    /**
     * <code>optional .fathomcloud.protobuf.ImageState image_state = 8;</code>
     */
    io.fathom.cloud.protobuf.ImageModel.ImageState getImageState();

    // optional uint64 created_at = 9;
    /**
     * <code>optional uint64 created_at = 9;</code>
     */
    boolean hasCreatedAt();
    /**
     * <code>optional uint64 created_at = 9;</code>
     */
    long getCreatedAt();

    // optional uint64 updated_at = 10;
    /**
     * <code>optional uint64 updated_at = 10;</code>
     */
    boolean hasUpdatedAt();
    /**
     * <code>optional uint64 updated_at = 10;</code>
     */
    long getUpdatedAt();

    // optional uint64 deleted_at = 15;
    /**
     * <code>optional uint64 deleted_at = 15;</code>
     */
    boolean hasDeletedAt();
    /**
     * <code>optional uint64 deleted_at = 15;</code>
     */
    long getDeletedAt();

    // optional uint64 owner_project = 11;
    /**
     * <code>optional uint64 owner_project = 11;</code>
     */
    boolean hasOwnerProject();
    /**
     * <code>optional uint64 owner_project = 11;</code>
     */
    long getOwnerProject();

    // optional uint64 image_size = 12;
    /**
     * <code>optional uint64 image_size = 12;</code>
     *
     * <pre>
     * A little redundant, but useful for remote images
     * </pre>
     */
    boolean hasImageSize();
    /**
     * <code>optional uint64 image_size = 12;</code>
     *
     * <pre>
     * A little redundant, but useful for remote images
     * </pre>
     */
    long getImageSize();

    // optional bytes image_checksum = 13;
    /**
     * <code>optional bytes image_checksum = 13;</code>
     */
    boolean hasImageChecksum();
    /**
     * <code>optional bytes image_checksum = 13;</code>
     */
    com.google.protobuf.ByteString getImageChecksum();

    // optional .fathomcloud.protobuf.Attributes attributes = 14;
    /**
     * <code>optional .fathomcloud.protobuf.Attributes attributes = 14;</code>
     */
    boolean hasAttributes();
    /**
     * <code>optional .fathomcloud.protobuf.Attributes attributes = 14;</code>
     */
    io.fathom.cloud.protobuf.CloudCommons.Attributes getAttributes();
    /**
     * <code>optional .fathomcloud.protobuf.Attributes attributes = 14;</code>
     */
    io.fathom.cloud.protobuf.CloudCommons.AttributesOrBuilder getAttributesOrBuilder();

    // optional bool is_protected = 16;
    /**
     * <code>optional bool is_protected = 16;</code>
     */
    boolean hasIsProtected();
    /**
     * <code>optional bool is_protected = 16;</code>
     */
    boolean getIsProtected();
  }
  /**
   * Protobuf type {@code fathomcloud.protobuf.ImageData}
   */
  public static final class ImageData extends
      com.google.protobuf.GeneratedMessage
      implements ImageDataOrBuilder {
    // Use ImageData.newBuilder() to construct.
    private ImageData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ImageData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ImageData defaultInstance;
    public static ImageData getDefaultInstance() {
      return defaultInstance;
    }

    public ImageData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ImageData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isPublic_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              diskFormat_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              containerFormat_ = input.readBytes();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                tag_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              tag_.add(input.readBytes());
              break;
            }
            case 58: {
              io.fathom.cloud.protobuf.ImageModel.ImageLocation.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = location_.toBuilder();
              }
              location_ = input.readMessage(io.fathom.cloud.protobuf.ImageModel.ImageLocation.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(location_);
                location_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              io.fathom.cloud.protobuf.ImageModel.ImageState value = io.fathom.cloud.protobuf.ImageModel.ImageState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                imageState_ = value;
              }
              break;
            }
            case 72: {
              bitField0_ |= 0x00000080;
              createdAt_ = input.readUInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000100;
              updatedAt_ = input.readUInt64();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              ownerProject_ = input.readUInt64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              imageSize_ = input.readUInt64();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              imageChecksum_ = input.readBytes();
              break;
            }
            case 114: {
              io.fathom.cloud.protobuf.CloudCommons.Attributes.Builder subBuilder = null;
              if (((bitField0_ & 0x00002000) == 0x00002000)) {
                subBuilder = attributes_.toBuilder();
              }
              attributes_ = input.readMessage(io.fathom.cloud.protobuf.CloudCommons.Attributes.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(attributes_);
                attributes_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00002000;
              break;
            }
            case 120: {
              bitField0_ |= 0x00000200;
              deletedAt_ = input.readUInt64();
              break;
            }
            case 128: {
              bitField0_ |= 0x00004000;
              isProtected_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          tag_ = new com.google.protobuf.UnmodifiableLazyStringList(tag_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.fathom.cloud.protobuf.ImageModel.internal_static_fathomcloud_protobuf_ImageData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.fathom.cloud.protobuf.ImageModel.internal_static_fathomcloud_protobuf_ImageData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.fathom.cloud.protobuf.ImageModel.ImageData.class, io.fathom.cloud.protobuf.ImageModel.ImageData.Builder.class);
    }

    public static com.google.protobuf.Parser<ImageData> PARSER =
        new com.google.protobuf.AbstractParser<ImageData>() {
      public ImageData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImageData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ImageData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // optional bool is_public = 2;
    public static final int IS_PUBLIC_FIELD_NUMBER = 2;
    private boolean isPublic_;
    /**
     * <code>optional bool is_public = 2;</code>
     */
    public boolean hasIsPublic() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool is_public = 2;</code>
     */
    public boolean getIsPublic() {
      return isPublic_;
    }

    // optional string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string disk_format = 4;
    public static final int DISK_FORMAT_FIELD_NUMBER = 4;
    private java.lang.Object diskFormat_;
    /**
     * <code>optional string disk_format = 4;</code>
     */
    public boolean hasDiskFormat() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string disk_format = 4;</code>
     */
    public java.lang.String getDiskFormat() {
      java.lang.Object ref = diskFormat_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          diskFormat_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string disk_format = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDiskFormatBytes() {
      java.lang.Object ref = diskFormat_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        diskFormat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string container_format = 5;
    public static final int CONTAINER_FORMAT_FIELD_NUMBER = 5;
    private java.lang.Object containerFormat_;
    /**
     * <code>optional string container_format = 5;</code>
     */
    public boolean hasContainerFormat() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string container_format = 5;</code>
     */
    public java.lang.String getContainerFormat() {
      java.lang.Object ref = containerFormat_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          containerFormat_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string container_format = 5;</code>
     */
    public com.google.protobuf.ByteString
        getContainerFormatBytes() {
      java.lang.Object ref = containerFormat_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        containerFormat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string tag = 6;
    public static final int TAG_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList tag_;
    /**
     * <code>repeated string tag = 6;</code>
     */
    public java.util.List<java.lang.String>
        getTagList() {
      return tag_;
    }
    /**
     * <code>repeated string tag = 6;</code>
     */
    public int getTagCount() {
      return tag_.size();
    }
    /**
     * <code>repeated string tag = 6;</code>
     */
    public java.lang.String getTag(int index) {
      return tag_.get(index);
    }
    /**
     * <code>repeated string tag = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTagBytes(int index) {
      return tag_.getByteString(index);
    }

    // optional .fathomcloud.protobuf.ImageLocation location = 7;
    public static final int LOCATION_FIELD_NUMBER = 7;
    private io.fathom.cloud.protobuf.ImageModel.ImageLocation location_;
    /**
     * <code>optional .fathomcloud.protobuf.ImageLocation location = 7;</code>
     */
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .fathomcloud.protobuf.ImageLocation location = 7;</code>
     */
    public io.fathom.cloud.protobuf.ImageModel.ImageLocation getLocation() {
      return location_;
    }
    /**
     * <code>optional .fathomcloud.protobuf.ImageLocation location = 7;</code>
     */
    public io.fathom.cloud.protobuf.ImageModel.ImageLocationOrBuilder getLocationOrBuilder() {
      return location_;
    }

    // optional .fathomcloud.protobuf.ImageState image_state = 8;
    public static final int IMAGE_STATE_FIELD_NUMBER = 8;
    private io.fathom.cloud.protobuf.ImageModel.ImageState imageState_;
    /**
     * <code>optional .fathomcloud.protobuf.ImageState image_state = 8;</code>
     */
    public boolean hasImageState() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .fathomcloud.protobuf.ImageState image_state = 8;</code>
     */
    public io.fathom.cloud.protobuf.ImageModel.ImageState getImageState() {
      return imageState_;
    }

    // optional uint64 created_at = 9;
    public static final int CREATED_AT_FIELD_NUMBER = 9;
    private long createdAt_;
    /**
     * <code>optional uint64 created_at = 9;</code>
     */
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint64 created_at = 9;</code>
     */
    public long getCreatedAt() {
      return createdAt_;
    }

    // optional uint64 updated_at = 10;
    public static final int UPDATED_AT_FIELD_NUMBER = 10;
    private long updatedAt_;
    /**
     * <code>optional uint64 updated_at = 10;</code>
     */
    public boolean hasUpdatedAt() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional uint64 updated_at = 10;</code>
     */
    public long getUpdatedAt() {
      return updatedAt_;
    }

    // optional uint64 deleted_at = 15;
    public static final int DELETED_AT_FIELD_NUMBER = 15;
    private long deletedAt_;
    /**
     * <code>optional uint64 deleted_at = 15;</code>
     */
    public boolean hasDeletedAt() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional uint64 deleted_at = 15;</code>
     */
    public long getDeletedAt() {
      return deletedAt_;
    }

    // optional uint64 owner_project = 11;
    public static final int OWNER_PROJECT_FIELD_NUMBER = 11;
    private long ownerProject_;
    /**
     * <code>optional uint64 owner_project = 11;</code>
     */
    public boolean hasOwnerProject() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional uint64 owner_project = 11;</code>
     */
    public long getOwnerProject() {
      return ownerProject_;
    }

    // optional uint64 image_size = 12;
    public static final int IMAGE_SIZE_FIELD_NUMBER = 12;
    private long imageSize_;
    /**
     * <code>optional uint64 image_size = 12;</code>
     *
     * <pre>
     * A little redundant, but useful for remote images
     * </pre>
     */
    public boolean hasImageSize() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional uint64 image_size = 12;</code>
     *
     * <pre>
     * A little redundant, but useful for remote images
     * </pre>
     */
    public long getImageSize() {
      return imageSize_;
    }

    // optional bytes image_checksum = 13;
    public static final int IMAGE_CHECKSUM_FIELD_NUMBER = 13;
    private com.google.protobuf.ByteString imageChecksum_;
    /**
     * <code>optional bytes image_checksum = 13;</code>
     */
    public boolean hasImageChecksum() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional bytes image_checksum = 13;</code>
     */
    public com.google.protobuf.ByteString getImageChecksum() {
      return imageChecksum_;
    }

    // optional .fathomcloud.protobuf.Attributes attributes = 14;
    public static final int ATTRIBUTES_FIELD_NUMBER = 14;
    private io.fathom.cloud.protobuf.CloudCommons.Attributes attributes_;
    /**
     * <code>optional .fathomcloud.protobuf.Attributes attributes = 14;</code>
     */
    public boolean hasAttributes() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional .fathomcloud.protobuf.Attributes attributes = 14;</code>
     */
    public io.fathom.cloud.protobuf.CloudCommons.Attributes getAttributes() {
      return attributes_;
    }
    /**
     * <code>optional .fathomcloud.protobuf.Attributes attributes = 14;</code>
     */
    public io.fathom.cloud.protobuf.CloudCommons.AttributesOrBuilder getAttributesOrBuilder() {
      return attributes_;
    }

    // optional bool is_protected = 16;
    public static final int IS_PROTECTED_FIELD_NUMBER = 16;
    private boolean isProtected_;
    /**
     * <code>optional bool is_protected = 16;</code>
     */
    public boolean hasIsProtected() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional bool is_protected = 16;</code>
     */
    public boolean getIsProtected() {
      return isProtected_;
    }

    private void initFields() {
      id_ = 0L;
      isPublic_ = false;
      name_ = "";
      diskFormat_ = "";
      containerFormat_ = "";
      tag_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      location_ = io.fathom.cloud.protobuf.ImageModel.ImageLocation.getDefaultInstance();
      imageState_ = io.fathom.cloud.protobuf.ImageModel.ImageState.QUEUED;
      createdAt_ = 0L;
      updatedAt_ = 0L;
      deletedAt_ = 0L;
      ownerProject_ = 0L;
      imageSize_ = 0L;
      imageChecksum_ = com.google.protobuf.ByteString.EMPTY;
      attributes_ = io.fathom.cloud.protobuf.CloudCommons.Attributes.getDefaultInstance();
      isProtected_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isPublic_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDiskFormatBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getContainerFormatBytes());
      }
      for (int i = 0; i < tag_.size(); i++) {
        output.writeBytes(6, tag_.getByteString(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(7, location_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(8, imageState_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt64(9, createdAt_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt64(10, updatedAt_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeUInt64(11, ownerProject_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeUInt64(12, imageSize_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, imageChecksum_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeMessage(14, attributes_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeUInt64(15, deletedAt_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBool(16, isProtected_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isPublic_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDiskFormatBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getContainerFormatBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < tag_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(tag_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTagList().size();
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, location_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, imageState_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(9, createdAt_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(10, updatedAt_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(11, ownerProject_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(12, imageSize_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, imageChecksum_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, attributes_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(15, deletedAt_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(16, isProtected_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.fathom.cloud.protobuf.ImageModel.ImageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.fathom.cloud.protobuf.ImageModel.ImageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.fathom.cloud.protobuf.ImageModel.ImageData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fathomcloud.protobuf.ImageData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements io.fathom.cloud.protobuf.ImageModel.ImageDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.fathom.cloud.protobuf.ImageModel.internal_static_fathomcloud_protobuf_ImageData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.fathom.cloud.protobuf.ImageModel.internal_static_fathomcloud_protobuf_ImageData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.fathom.cloud.protobuf.ImageModel.ImageData.class, io.fathom.cloud.protobuf.ImageModel.ImageData.Builder.class);
      }

      // Construct using io.fathom.cloud.protobuf.ImageModel.ImageData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLocationFieldBuilder();
          getAttributesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        isPublic_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        diskFormat_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        containerFormat_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        tag_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (locationBuilder_ == null) {
          location_ = io.fathom.cloud.protobuf.ImageModel.ImageLocation.getDefaultInstance();
        } else {
          locationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        imageState_ = io.fathom.cloud.protobuf.ImageModel.ImageState.QUEUED;
        bitField0_ = (bitField0_ & ~0x00000080);
        createdAt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        updatedAt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        deletedAt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        ownerProject_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        imageSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00001000);
        imageChecksum_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00002000);
        if (attributesBuilder_ == null) {
          attributes_ = io.fathom.cloud.protobuf.CloudCommons.Attributes.getDefaultInstance();
        } else {
          attributesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00004000);
        isProtected_ = false;
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.fathom.cloud.protobuf.ImageModel.internal_static_fathomcloud_protobuf_ImageData_descriptor;
      }

      public io.fathom.cloud.protobuf.ImageModel.ImageData getDefaultInstanceForType() {
        return io.fathom.cloud.protobuf.ImageModel.ImageData.getDefaultInstance();
      }

      public io.fathom.cloud.protobuf.ImageModel.ImageData build() {
        io.fathom.cloud.protobuf.ImageModel.ImageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.fathom.cloud.protobuf.ImageModel.ImageData buildPartial() {
        io.fathom.cloud.protobuf.ImageModel.ImageData result = new io.fathom.cloud.protobuf.ImageModel.ImageData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isPublic_ = isPublic_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.diskFormat_ = diskFormat_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.containerFormat_ = containerFormat_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          tag_ = new com.google.protobuf.UnmodifiableLazyStringList(
              tag_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.tag_ = tag_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        if (locationBuilder_ == null) {
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.imageState_ = imageState_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.createdAt_ = createdAt_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.updatedAt_ = updatedAt_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.deletedAt_ = deletedAt_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000400;
        }
        result.ownerProject_ = ownerProject_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00000800;
        }
        result.imageSize_ = imageSize_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.imageChecksum_ = imageChecksum_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00002000;
        }
        if (attributesBuilder_ == null) {
          result.attributes_ = attributes_;
        } else {
          result.attributes_ = attributesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.isProtected_ = isProtected_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.fathom.cloud.protobuf.ImageModel.ImageData) {
          return mergeFrom((io.fathom.cloud.protobuf.ImageModel.ImageData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.fathom.cloud.protobuf.ImageModel.ImageData other) {
        if (other == io.fathom.cloud.protobuf.ImageModel.ImageData.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasIsPublic()) {
          setIsPublic(other.getIsPublic());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasDiskFormat()) {
          bitField0_ |= 0x00000008;
          diskFormat_ = other.diskFormat_;
          onChanged();
        }
        if (other.hasContainerFormat()) {
          bitField0_ |= 0x00000010;
          containerFormat_ = other.containerFormat_;
          onChanged();
        }
        if (!other.tag_.isEmpty()) {
          if (tag_.isEmpty()) {
            tag_ = other.tag_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureTagIsMutable();
            tag_.addAll(other.tag_);
          }
          onChanged();
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        if (other.hasImageState()) {
          setImageState(other.getImageState());
        }
        if (other.hasCreatedAt()) {
          setCreatedAt(other.getCreatedAt());
        }
        if (other.hasUpdatedAt()) {
          setUpdatedAt(other.getUpdatedAt());
        }
        if (other.hasDeletedAt()) {
          setDeletedAt(other.getDeletedAt());
        }
        if (other.hasOwnerProject()) {
          setOwnerProject(other.getOwnerProject());
        }
        if (other.hasImageSize()) {
          setImageSize(other.getImageSize());
        }
        if (other.hasImageChecksum()) {
          setImageChecksum(other.getImageChecksum());
        }
        if (other.hasAttributes()) {
          mergeAttributes(other.getAttributes());
        }
        if (other.hasIsProtected()) {
          setIsProtected(other.getIsProtected());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.fathom.cloud.protobuf.ImageModel.ImageData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.fathom.cloud.protobuf.ImageModel.ImageData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 id = 1;
      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // optional bool is_public = 2;
      private boolean isPublic_ ;
      /**
       * <code>optional bool is_public = 2;</code>
       */
      public boolean hasIsPublic() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool is_public = 2;</code>
       */
      public boolean getIsPublic() {
        return isPublic_;
      }
      /**
       * <code>optional bool is_public = 2;</code>
       */
      public Builder setIsPublic(boolean value) {
        bitField0_ |= 0x00000002;
        isPublic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_public = 2;</code>
       */
      public Builder clearIsPublic() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isPublic_ = false;
        onChanged();
        return this;
      }

      // optional string name = 3;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string disk_format = 4;
      private java.lang.Object diskFormat_ = "";
      /**
       * <code>optional string disk_format = 4;</code>
       */
      public boolean hasDiskFormat() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string disk_format = 4;</code>
       */
      public java.lang.String getDiskFormat() {
        java.lang.Object ref = diskFormat_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          diskFormat_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string disk_format = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDiskFormatBytes() {
        java.lang.Object ref = diskFormat_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          diskFormat_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string disk_format = 4;</code>
       */
      public Builder setDiskFormat(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        diskFormat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string disk_format = 4;</code>
       */
      public Builder clearDiskFormat() {
        bitField0_ = (bitField0_ & ~0x00000008);
        diskFormat_ = getDefaultInstance().getDiskFormat();
        onChanged();
        return this;
      }
      /**
       * <code>optional string disk_format = 4;</code>
       */
      public Builder setDiskFormatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        diskFormat_ = value;
        onChanged();
        return this;
      }

      // optional string container_format = 5;
      private java.lang.Object containerFormat_ = "";
      /**
       * <code>optional string container_format = 5;</code>
       */
      public boolean hasContainerFormat() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string container_format = 5;</code>
       */
      public java.lang.String getContainerFormat() {
        java.lang.Object ref = containerFormat_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          containerFormat_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string container_format = 5;</code>
       */
      public com.google.protobuf.ByteString
          getContainerFormatBytes() {
        java.lang.Object ref = containerFormat_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          containerFormat_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string container_format = 5;</code>
       */
      public Builder setContainerFormat(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        containerFormat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string container_format = 5;</code>
       */
      public Builder clearContainerFormat() {
        bitField0_ = (bitField0_ & ~0x00000010);
        containerFormat_ = getDefaultInstance().getContainerFormat();
        onChanged();
        return this;
      }
      /**
       * <code>optional string container_format = 5;</code>
       */
      public Builder setContainerFormatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        containerFormat_ = value;
        onChanged();
        return this;
      }

      // repeated string tag = 6;
      private com.google.protobuf.LazyStringList tag_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTagIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          tag_ = new com.google.protobuf.LazyStringArrayList(tag_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string tag = 6;</code>
       */
      public java.util.List<java.lang.String>
          getTagList() {
        return java.util.Collections.unmodifiableList(tag_);
      }
      /**
       * <code>repeated string tag = 6;</code>
       */
      public int getTagCount() {
        return tag_.size();
      }
      /**
       * <code>repeated string tag = 6;</code>
       */
      public java.lang.String getTag(int index) {
        return tag_.get(index);
      }
      /**
       * <code>repeated string tag = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTagBytes(int index) {
        return tag_.getByteString(index);
      }
      /**
       * <code>repeated string tag = 6;</code>
       */
      public Builder setTag(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagIsMutable();
        tag_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tag = 6;</code>
       */
      public Builder addTag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagIsMutable();
        tag_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tag = 6;</code>
       */
      public Builder addAllTag(
          java.lang.Iterable<java.lang.String> values) {
        ensureTagIsMutable();
        super.addAll(values, tag_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tag = 6;</code>
       */
      public Builder clearTag() {
        tag_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tag = 6;</code>
       */
      public Builder addTagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagIsMutable();
        tag_.add(value);
        onChanged();
        return this;
      }

      // optional .fathomcloud.protobuf.ImageLocation location = 7;
      private io.fathom.cloud.protobuf.ImageModel.ImageLocation location_ = io.fathom.cloud.protobuf.ImageModel.ImageLocation.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          io.fathom.cloud.protobuf.ImageModel.ImageLocation, io.fathom.cloud.protobuf.ImageModel.ImageLocation.Builder, io.fathom.cloud.protobuf.ImageModel.ImageLocationOrBuilder> locationBuilder_;
      /**
       * <code>optional .fathomcloud.protobuf.ImageLocation location = 7;</code>
       */
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .fathomcloud.protobuf.ImageLocation location = 7;</code>
       */
      public io.fathom.cloud.protobuf.ImageModel.ImageLocation getLocation() {
        if (locationBuilder_ == null) {
          return location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .fathomcloud.protobuf.ImageLocation location = 7;</code>
       */
      public Builder setLocation(io.fathom.cloud.protobuf.ImageModel.ImageLocation value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
          onChanged();
        } else {
          locationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .fathomcloud.protobuf.ImageLocation location = 7;</code>
       */
      public Builder setLocation(
          io.fathom.cloud.protobuf.ImageModel.ImageLocation.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
          onChanged();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .fathomcloud.protobuf.ImageLocation location = 7;</code>
       */
      public Builder mergeLocation(io.fathom.cloud.protobuf.ImageModel.ImageLocation value) {
        if (locationBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              location_ != io.fathom.cloud.protobuf.ImageModel.ImageLocation.getDefaultInstance()) {
            location_ =
              io.fathom.cloud.protobuf.ImageModel.ImageLocation.newBuilder(location_).mergeFrom(value).buildPartial();
          } else {
            location_ = value;
          }
          onChanged();
        } else {
          locationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .fathomcloud.protobuf.ImageLocation location = 7;</code>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = io.fathom.cloud.protobuf.ImageModel.ImageLocation.getDefaultInstance();
          onChanged();
        } else {
          locationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .fathomcloud.protobuf.ImageLocation location = 7;</code>
       */
      public io.fathom.cloud.protobuf.ImageModel.ImageLocation.Builder getLocationBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .fathomcloud.protobuf.ImageLocation location = 7;</code>
       */
      public io.fathom.cloud.protobuf.ImageModel.ImageLocationOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_;
        }
      }
      /**
       * <code>optional .fathomcloud.protobuf.ImageLocation location = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          io.fathom.cloud.protobuf.ImageModel.ImageLocation, io.fathom.cloud.protobuf.ImageModel.ImageLocation.Builder, io.fathom.cloud.protobuf.ImageModel.ImageLocationOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              io.fathom.cloud.protobuf.ImageModel.ImageLocation, io.fathom.cloud.protobuf.ImageModel.ImageLocation.Builder, io.fathom.cloud.protobuf.ImageModel.ImageLocationOrBuilder>(
                  location_,
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      // optional .fathomcloud.protobuf.ImageState image_state = 8;
      private io.fathom.cloud.protobuf.ImageModel.ImageState imageState_ = io.fathom.cloud.protobuf.ImageModel.ImageState.QUEUED;
      /**
       * <code>optional .fathomcloud.protobuf.ImageState image_state = 8;</code>
       */
      public boolean hasImageState() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .fathomcloud.protobuf.ImageState image_state = 8;</code>
       */
      public io.fathom.cloud.protobuf.ImageModel.ImageState getImageState() {
        return imageState_;
      }
      /**
       * <code>optional .fathomcloud.protobuf.ImageState image_state = 8;</code>
       */
      public Builder setImageState(io.fathom.cloud.protobuf.ImageModel.ImageState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        imageState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .fathomcloud.protobuf.ImageState image_state = 8;</code>
       */
      public Builder clearImageState() {
        bitField0_ = (bitField0_ & ~0x00000080);
        imageState_ = io.fathom.cloud.protobuf.ImageModel.ImageState.QUEUED;
        onChanged();
        return this;
      }

      // optional uint64 created_at = 9;
      private long createdAt_ ;
      /**
       * <code>optional uint64 created_at = 9;</code>
       */
      public boolean hasCreatedAt() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional uint64 created_at = 9;</code>
       */
      public long getCreatedAt() {
        return createdAt_;
      }
      /**
       * <code>optional uint64 created_at = 9;</code>
       */
      public Builder setCreatedAt(long value) {
        bitField0_ |= 0x00000100;
        createdAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 created_at = 9;</code>
       */
      public Builder clearCreatedAt() {
        bitField0_ = (bitField0_ & ~0x00000100);
        createdAt_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 updated_at = 10;
      private long updatedAt_ ;
      /**
       * <code>optional uint64 updated_at = 10;</code>
       */
      public boolean hasUpdatedAt() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional uint64 updated_at = 10;</code>
       */
      public long getUpdatedAt() {
        return updatedAt_;
      }
      /**
       * <code>optional uint64 updated_at = 10;</code>
       */
      public Builder setUpdatedAt(long value) {
        bitField0_ |= 0x00000200;
        updatedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 updated_at = 10;</code>
       */
      public Builder clearUpdatedAt() {
        bitField0_ = (bitField0_ & ~0x00000200);
        updatedAt_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 deleted_at = 15;
      private long deletedAt_ ;
      /**
       * <code>optional uint64 deleted_at = 15;</code>
       */
      public boolean hasDeletedAt() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional uint64 deleted_at = 15;</code>
       */
      public long getDeletedAt() {
        return deletedAt_;
      }
      /**
       * <code>optional uint64 deleted_at = 15;</code>
       */
      public Builder setDeletedAt(long value) {
        bitField0_ |= 0x00000400;
        deletedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 deleted_at = 15;</code>
       */
      public Builder clearDeletedAt() {
        bitField0_ = (bitField0_ & ~0x00000400);
        deletedAt_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 owner_project = 11;
      private long ownerProject_ ;
      /**
       * <code>optional uint64 owner_project = 11;</code>
       */
      public boolean hasOwnerProject() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional uint64 owner_project = 11;</code>
       */
      public long getOwnerProject() {
        return ownerProject_;
      }
      /**
       * <code>optional uint64 owner_project = 11;</code>
       */
      public Builder setOwnerProject(long value) {
        bitField0_ |= 0x00000800;
        ownerProject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 owner_project = 11;</code>
       */
      public Builder clearOwnerProject() {
        bitField0_ = (bitField0_ & ~0x00000800);
        ownerProject_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 image_size = 12;
      private long imageSize_ ;
      /**
       * <code>optional uint64 image_size = 12;</code>
       *
       * <pre>
       * A little redundant, but useful for remote images
       * </pre>
       */
      public boolean hasImageSize() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional uint64 image_size = 12;</code>
       *
       * <pre>
       * A little redundant, but useful for remote images
       * </pre>
       */
      public long getImageSize() {
        return imageSize_;
      }
      /**
       * <code>optional uint64 image_size = 12;</code>
       *
       * <pre>
       * A little redundant, but useful for remote images
       * </pre>
       */
      public Builder setImageSize(long value) {
        bitField0_ |= 0x00001000;
        imageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 image_size = 12;</code>
       *
       * <pre>
       * A little redundant, but useful for remote images
       * </pre>
       */
      public Builder clearImageSize() {
        bitField0_ = (bitField0_ & ~0x00001000);
        imageSize_ = 0L;
        onChanged();
        return this;
      }

      // optional bytes image_checksum = 13;
      private com.google.protobuf.ByteString imageChecksum_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes image_checksum = 13;</code>
       */
      public boolean hasImageChecksum() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional bytes image_checksum = 13;</code>
       */
      public com.google.protobuf.ByteString getImageChecksum() {
        return imageChecksum_;
      }
      /**
       * <code>optional bytes image_checksum = 13;</code>
       */
      public Builder setImageChecksum(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        imageChecksum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes image_checksum = 13;</code>
       */
      public Builder clearImageChecksum() {
        bitField0_ = (bitField0_ & ~0x00002000);
        imageChecksum_ = getDefaultInstance().getImageChecksum();
        onChanged();
        return this;
      }

      // optional .fathomcloud.protobuf.Attributes attributes = 14;
      private io.fathom.cloud.protobuf.CloudCommons.Attributes attributes_ = io.fathom.cloud.protobuf.CloudCommons.Attributes.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          io.fathom.cloud.protobuf.CloudCommons.Attributes, io.fathom.cloud.protobuf.CloudCommons.Attributes.Builder, io.fathom.cloud.protobuf.CloudCommons.AttributesOrBuilder> attributesBuilder_;
      /**
       * <code>optional .fathomcloud.protobuf.Attributes attributes = 14;</code>
       */
      public boolean hasAttributes() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional .fathomcloud.protobuf.Attributes attributes = 14;</code>
       */
      public io.fathom.cloud.protobuf.CloudCommons.Attributes getAttributes() {
        if (attributesBuilder_ == null) {
          return attributes_;
        } else {
          return attributesBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .fathomcloud.protobuf.Attributes attributes = 14;</code>
       */
      public Builder setAttributes(io.fathom.cloud.protobuf.CloudCommons.Attributes value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          attributes_ = value;
          onChanged();
        } else {
          attributesBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00004000;
        return this;
      }
      /**
       * <code>optional .fathomcloud.protobuf.Attributes attributes = 14;</code>
       */
      public Builder setAttributes(
          io.fathom.cloud.protobuf.CloudCommons.Attributes.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          attributes_ = builderForValue.build();
          onChanged();
        } else {
          attributesBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00004000;
        return this;
      }
      /**
       * <code>optional .fathomcloud.protobuf.Attributes attributes = 14;</code>
       */
      public Builder mergeAttributes(io.fathom.cloud.protobuf.CloudCommons.Attributes value) {
        if (attributesBuilder_ == null) {
          if (((bitField0_ & 0x00004000) == 0x00004000) &&
              attributes_ != io.fathom.cloud.protobuf.CloudCommons.Attributes.getDefaultInstance()) {
            attributes_ =
              io.fathom.cloud.protobuf.CloudCommons.Attributes.newBuilder(attributes_).mergeFrom(value).buildPartial();
          } else {
            attributes_ = value;
          }
          onChanged();
        } else {
          attributesBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00004000;
        return this;
      }
      /**
       * <code>optional .fathomcloud.protobuf.Attributes attributes = 14;</code>
       */
      public Builder clearAttributes() {
        if (attributesBuilder_ == null) {
          attributes_ = io.fathom.cloud.protobuf.CloudCommons.Attributes.getDefaultInstance();
          onChanged();
        } else {
          attributesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00004000);
        return this;
      }
      /**
       * <code>optional .fathomcloud.protobuf.Attributes attributes = 14;</code>
       */
      public io.fathom.cloud.protobuf.CloudCommons.Attributes.Builder getAttributesBuilder() {
        bitField0_ |= 0x00004000;
        onChanged();
        return getAttributesFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .fathomcloud.protobuf.Attributes attributes = 14;</code>
       */
      public io.fathom.cloud.protobuf.CloudCommons.AttributesOrBuilder getAttributesOrBuilder() {
        if (attributesBuilder_ != null) {
          return attributesBuilder_.getMessageOrBuilder();
        } else {
          return attributes_;
        }
      }
      /**
       * <code>optional .fathomcloud.protobuf.Attributes attributes = 14;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          io.fathom.cloud.protobuf.CloudCommons.Attributes, io.fathom.cloud.protobuf.CloudCommons.Attributes.Builder, io.fathom.cloud.protobuf.CloudCommons.AttributesOrBuilder> 
          getAttributesFieldBuilder() {
        if (attributesBuilder_ == null) {
          attributesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              io.fathom.cloud.protobuf.CloudCommons.Attributes, io.fathom.cloud.protobuf.CloudCommons.Attributes.Builder, io.fathom.cloud.protobuf.CloudCommons.AttributesOrBuilder>(
                  attributes_,
                  getParentForChildren(),
                  isClean());
          attributes_ = null;
        }
        return attributesBuilder_;
      }

      // optional bool is_protected = 16;
      private boolean isProtected_ ;
      /**
       * <code>optional bool is_protected = 16;</code>
       */
      public boolean hasIsProtected() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional bool is_protected = 16;</code>
       */
      public boolean getIsProtected() {
        return isProtected_;
      }
      /**
       * <code>optional bool is_protected = 16;</code>
       */
      public Builder setIsProtected(boolean value) {
        bitField0_ |= 0x00008000;
        isProtected_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_protected = 16;</code>
       */
      public Builder clearIsProtected() {
        bitField0_ = (bitField0_ & ~0x00008000);
        isProtected_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:fathomcloud.protobuf.ImageData)
    }

    static {
      defaultInstance = new ImageData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:fathomcloud.protobuf.ImageData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_fathomcloud_protobuf_ImageLocation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fathomcloud_protobuf_ImageLocation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_fathomcloud_protobuf_ImageData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fathomcloud_protobuf_ImageData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ImageModel.proto\022\024fathomcloud.protobuf" +
      "\032\022CloudCommons.proto\"\037\n\rImageLocation\022\016\n" +
      "\006stored\030\001 \001(\t\"\255\003\n\tImageData\022\n\n\002id\030\001 \001(\003\022" +
      "\021\n\tis_public\030\002 \001(\010\022\014\n\004name\030\003 \001(\t\022\023\n\013disk" +
      "_format\030\004 \001(\t\022\030\n\020container_format\030\005 \001(\t\022" +
      "\013\n\003tag\030\006 \003(\t\0225\n\010location\030\007 \001(\0132#.fathomc" +
      "loud.protobuf.ImageLocation\0225\n\013image_sta" +
      "te\030\010 \001(\0162 .fathomcloud.protobuf.ImageSta" +
      "te\022\022\n\ncreated_at\030\t \001(\004\022\022\n\nupdated_at\030\n \001" +
      "(\004\022\022\n\ndeleted_at\030\017 \001(\004\022\025\n\rowner_project\030",
      "\013 \001(\004\022\022\n\nimage_size\030\014 \001(\004\022\026\n\016image_check" +
      "sum\030\r \001(\014\0224\n\nattributes\030\016 \001(\0132 .fathomcl" +
      "oud.protobuf.Attributes\022\024\n\014is_protected\030" +
      "\020 \001(\010*]\n\nImageState\022\n\n\006QUEUED\020\001\022\n\n\006SAVIN" +
      "G\020\002\022\n\n\006ACTIVE\020\003\022\n\n\006KILLED\020\004\022\013\n\007DELETED\020\005" +
      "\022\022\n\016PENDING_DELETE\020\006B\032\n\030io.fathom.cloud." +
      "protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_fathomcloud_protobuf_ImageLocation_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_fathomcloud_protobuf_ImageLocation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_fathomcloud_protobuf_ImageLocation_descriptor,
              new java.lang.String[] { "Stored", });
          internal_static_fathomcloud_protobuf_ImageData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_fathomcloud_protobuf_ImageData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_fathomcloud_protobuf_ImageData_descriptor,
              new java.lang.String[] { "Id", "IsPublic", "Name", "DiskFormat", "ContainerFormat", "Tag", "Location", "ImageState", "CreatedAt", "UpdatedAt", "DeletedAt", "OwnerProject", "ImageSize", "ImageChecksum", "Attributes", "IsProtected", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.fathom.cloud.protobuf.CloudCommons.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
