// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecretsModel.proto

package io.fathom.cloud.protobuf;

public final class SecretsModel {
  private SecretsModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SecretRecordItemDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string key = 1;
    boolean hasKey();
    String getKey();
    
    // optional bytes ciphertext = 2;
    boolean hasCiphertext();
    com.google.protobuf.ByteString getCiphertext();
  }
  public static final class SecretRecordItemData extends
      com.google.protobuf.GeneratedMessage
      implements SecretRecordItemDataOrBuilder {
    // Use SecretRecordItemData.newBuilder() to construct.
    private SecretRecordItemData(Builder builder) {
      super(builder);
    }
    private SecretRecordItemData(boolean noInit) {}
    
    private static final SecretRecordItemData defaultInstance;
    public static SecretRecordItemData getDefaultInstance() {
      return defaultInstance;
    }
    
    public SecretRecordItemData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.fathom.cloud.protobuf.SecretsModel.internal_static_fathomcloud_protobuf_SecretRecordItemData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.fathom.cloud.protobuf.SecretsModel.internal_static_fathomcloud_protobuf_SecretRecordItemData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes ciphertext = 2;
    public static final int CIPHERTEXT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString ciphertext_;
    public boolean hasCiphertext() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getCiphertext() {
      return ciphertext_;
    }
    
    private void initFields() {
      key_ = "";
      ciphertext_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, ciphertext_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, ciphertext_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.fathom.cloud.protobuf.SecretsModel.internal_static_fathomcloud_protobuf_SecretRecordItemData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.fathom.cloud.protobuf.SecretsModel.internal_static_fathomcloud_protobuf_SecretRecordItemData_fieldAccessorTable;
      }
      
      // Construct using io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        ciphertext_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.getDescriptor();
      }
      
      public io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData getDefaultInstanceForType() {
        return io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.getDefaultInstance();
      }
      
      public io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData build() {
        io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData buildPartial() {
        io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData result = new io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ciphertext_ = ciphertext_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData) {
          return mergeFrom((io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData other) {
        if (other == io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasCiphertext()) {
          setCiphertext(other.getCiphertext());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              ciphertext_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string key = 1;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
      }
      
      // optional bytes ciphertext = 2;
      private com.google.protobuf.ByteString ciphertext_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasCiphertext() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getCiphertext() {
        return ciphertext_;
      }
      public Builder setCiphertext(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ciphertext_ = value;
        onChanged();
        return this;
      }
      public Builder clearCiphertext() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ciphertext_ = getDefaultInstance().getCiphertext();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:fathomcloud.protobuf.SecretRecordItemData)
    }
    
    static {
      defaultInstance = new SecretRecordItemData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:fathomcloud.protobuf.SecretRecordItemData)
  }
  
  public interface SecretRecordDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 id = 1;
    boolean hasId();
    long getId();
    
    // repeated .fathomcloud.protobuf.SecretRecordItemData item = 2;
    java.util.List<io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData> 
        getItemList();
    io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData getItem(int index);
    int getItemCount();
    java.util.List<? extends io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemDataOrBuilder> 
        getItemOrBuilderList();
    io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemDataOrBuilder getItemOrBuilder(
        int index);
    
    // optional string name = 3;
    boolean hasName();
    String getName();
    
    // optional string algorithm = 4;
    boolean hasAlgorithm();
    String getAlgorithm();
    
    // optional int32 key_size = 5;
    boolean hasKeySize();
    int getKeySize();
    
    // optional string subject = 6;
    boolean hasSubject();
    String getSubject();
  }
  public static final class SecretRecordData extends
      com.google.protobuf.GeneratedMessage
      implements SecretRecordDataOrBuilder {
    // Use SecretRecordData.newBuilder() to construct.
    private SecretRecordData(Builder builder) {
      super(builder);
    }
    private SecretRecordData(boolean noInit) {}
    
    private static final SecretRecordData defaultInstance;
    public static SecretRecordData getDefaultInstance() {
      return defaultInstance;
    }
    
    public SecretRecordData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.fathom.cloud.protobuf.SecretsModel.internal_static_fathomcloud_protobuf_SecretRecordData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.fathom.cloud.protobuf.SecretsModel.internal_static_fathomcloud_protobuf_SecretRecordData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // repeated .fathomcloud.protobuf.SecretRecordItemData item = 2;
    public static final int ITEM_FIELD_NUMBER = 2;
    private java.util.List<io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData> item_;
    public java.util.List<io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData> getItemList() {
      return item_;
    }
    public java.util.List<? extends io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemDataOrBuilder> 
        getItemOrBuilderList() {
      return item_;
    }
    public int getItemCount() {
      return item_.size();
    }
    public io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData getItem(int index) {
      return item_.get(index);
    }
    public io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemDataOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }
    
    // optional string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string algorithm = 4;
    public static final int ALGORITHM_FIELD_NUMBER = 4;
    private java.lang.Object algorithm_;
    public boolean hasAlgorithm() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getAlgorithm() {
      java.lang.Object ref = algorithm_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          algorithm_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAlgorithmBytes() {
      java.lang.Object ref = algorithm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        algorithm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 key_size = 5;
    public static final int KEY_SIZE_FIELD_NUMBER = 5;
    private int keySize_;
    public boolean hasKeySize() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getKeySize() {
      return keySize_;
    }
    
    // optional string subject = 6;
    public static final int SUBJECT_FIELD_NUMBER = 6;
    private java.lang.Object subject_;
    public boolean hasSubject() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getSubject() {
      java.lang.Object ref = subject_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          subject_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = 0L;
      item_ = java.util.Collections.emptyList();
      name_ = "";
      algorithm_ = "";
      keySize_ = 0;
      subject_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(2, item_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getAlgorithmBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(5, keySize_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getSubjectBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, item_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAlgorithmBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, keySize_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getSubjectBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static io.fathom.cloud.protobuf.SecretsModel.SecretRecordData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.fathom.cloud.protobuf.SecretsModel.SecretRecordData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements io.fathom.cloud.protobuf.SecretsModel.SecretRecordDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.fathom.cloud.protobuf.SecretsModel.internal_static_fathomcloud_protobuf_SecretRecordData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.fathom.cloud.protobuf.SecretsModel.internal_static_fathomcloud_protobuf_SecretRecordData_fieldAccessorTable;
      }
      
      // Construct using io.fathom.cloud.protobuf.SecretsModel.SecretRecordData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          itemBuilder_.clear();
        }
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        algorithm_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        keySize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        subject_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.fathom.cloud.protobuf.SecretsModel.SecretRecordData.getDescriptor();
      }
      
      public io.fathom.cloud.protobuf.SecretsModel.SecretRecordData getDefaultInstanceForType() {
        return io.fathom.cloud.protobuf.SecretsModel.SecretRecordData.getDefaultInstance();
      }
      
      public io.fathom.cloud.protobuf.SecretsModel.SecretRecordData build() {
        io.fathom.cloud.protobuf.SecretsModel.SecretRecordData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private io.fathom.cloud.protobuf.SecretsModel.SecretRecordData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        io.fathom.cloud.protobuf.SecretsModel.SecretRecordData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public io.fathom.cloud.protobuf.SecretsModel.SecretRecordData buildPartial() {
        io.fathom.cloud.protobuf.SecretsModel.SecretRecordData result = new io.fathom.cloud.protobuf.SecretsModel.SecretRecordData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            item_ = java.util.Collections.unmodifiableList(item_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.algorithm_ = algorithm_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.keySize_ = keySize_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.subject_ = subject_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.fathom.cloud.protobuf.SecretsModel.SecretRecordData) {
          return mergeFrom((io.fathom.cloud.protobuf.SecretsModel.SecretRecordData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(io.fathom.cloud.protobuf.SecretsModel.SecretRecordData other) {
        if (other == io.fathom.cloud.protobuf.SecretsModel.SecretRecordData.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (itemBuilder_ == null) {
          if (!other.item_.isEmpty()) {
            if (item_.isEmpty()) {
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureItemIsMutable();
              item_.addAll(other.item_);
            }
            onChanged();
          }
        } else {
          if (!other.item_.isEmpty()) {
            if (itemBuilder_.isEmpty()) {
              itemBuilder_.dispose();
              itemBuilder_ = null;
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000002);
              itemBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemFieldBuilder() : null;
            } else {
              itemBuilder_.addAllMessages(other.item_);
            }
          }
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasAlgorithm()) {
          setAlgorithm(other.getAlgorithm());
        }
        if (other.hasKeySize()) {
          setKeySize(other.getKeySize());
        }
        if (other.hasSubject()) {
          setSubject(other.getSubject());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.Builder subBuilder = io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addItem(subBuilder.buildPartial());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              algorithm_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              keySize_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              subject_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .fathomcloud.protobuf.SecretRecordItemData item = 2;
      private java.util.List<io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData> item_ =
        java.util.Collections.emptyList();
      private void ensureItemIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          item_ = new java.util.ArrayList<io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData>(item_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData, io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.Builder, io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemDataOrBuilder> itemBuilder_;
      
      public java.util.List<io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData> getItemList() {
        if (itemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(item_);
        } else {
          return itemBuilder_.getMessageList();
        }
      }
      public int getItemCount() {
        if (itemBuilder_ == null) {
          return item_.size();
        } else {
          return itemBuilder_.getCount();
        }
      }
      public io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData getItem(int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);
        } else {
          return itemBuilder_.getMessage(index);
        }
      }
      public Builder setItem(
          int index, io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.set(index, value);
          onChanged();
        } else {
          itemBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setItem(
          int index, io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addItem(io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(value);
          onChanged();
        } else {
          itemBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addItem(
          int index, io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(index, value);
          onChanged();
        } else {
          itemBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addItem(
          io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addItem(
          int index, io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllItem(
          java.lang.Iterable<? extends io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData> values) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          super.addAll(values, item_);
          onChanged();
        } else {
          itemBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        return this;
      }
      public Builder removeItem(int index) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.remove(index);
          onChanged();
        } else {
          itemBuilder_.remove(index);
        }
        return this;
      }
      public io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.Builder getItemBuilder(
          int index) {
        return getItemFieldBuilder().getBuilder(index);
      }
      public io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemDataOrBuilder getItemOrBuilder(
          int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);  } else {
          return itemBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemDataOrBuilder> 
           getItemOrBuilderList() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(item_);
        }
      }
      public io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.Builder addItemBuilder() {
        return getItemFieldBuilder().addBuilder(
            io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.getDefaultInstance());
      }
      public io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.Builder addItemBuilder(
          int index) {
        return getItemFieldBuilder().addBuilder(
            index, io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.getDefaultInstance());
      }
      public java.util.List<io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.Builder> 
           getItemBuilderList() {
        return getItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData, io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.Builder, io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemDataOrBuilder> 
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData, io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.Builder, io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemDataOrBuilder>(
                  item_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }
      
      // optional string name = 3;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
      }
      
      // optional string algorithm = 4;
      private java.lang.Object algorithm_ = "";
      public boolean hasAlgorithm() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getAlgorithm() {
        java.lang.Object ref = algorithm_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          algorithm_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAlgorithm(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        algorithm_ = value;
        onChanged();
        return this;
      }
      public Builder clearAlgorithm() {
        bitField0_ = (bitField0_ & ~0x00000008);
        algorithm_ = getDefaultInstance().getAlgorithm();
        onChanged();
        return this;
      }
      void setAlgorithm(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        algorithm_ = value;
        onChanged();
      }
      
      // optional int32 key_size = 5;
      private int keySize_ ;
      public boolean hasKeySize() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getKeySize() {
        return keySize_;
      }
      public Builder setKeySize(int value) {
        bitField0_ |= 0x00000010;
        keySize_ = value;
        onChanged();
        return this;
      }
      public Builder clearKeySize() {
        bitField0_ = (bitField0_ & ~0x00000010);
        keySize_ = 0;
        onChanged();
        return this;
      }
      
      // optional string subject = 6;
      private java.lang.Object subject_ = "";
      public boolean hasSubject() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getSubject() {
        java.lang.Object ref = subject_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          subject_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSubject(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        subject_ = value;
        onChanged();
        return this;
      }
      public Builder clearSubject() {
        bitField0_ = (bitField0_ & ~0x00000020);
        subject_ = getDefaultInstance().getSubject();
        onChanged();
        return this;
      }
      void setSubject(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        subject_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:fathomcloud.protobuf.SecretRecordData)
    }
    
    static {
      defaultInstance = new SecretRecordData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:fathomcloud.protobuf.SecretRecordData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_fathomcloud_protobuf_SecretRecordItemData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fathomcloud_protobuf_SecretRecordItemData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_fathomcloud_protobuf_SecretRecordData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fathomcloud_protobuf_SecretRecordData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SecretsModel.proto\022\024fathomcloud.protob" +
      "uf\032\022CloudCommons.proto\"7\n\024SecretRecordIt" +
      "emData\022\013\n\003key\030\001 \001(\t\022\022\n\nciphertext\030\002 \001(\014\"" +
      "\234\001\n\020SecretRecordData\022\n\n\002id\030\001 \001(\003\0228\n\004item" +
      "\030\002 \003(\0132*.fathomcloud.protobuf.SecretReco" +
      "rdItemData\022\014\n\004name\030\003 \001(\t\022\021\n\talgorithm\030\004 " +
      "\001(\t\022\020\n\010key_size\030\005 \001(\005\022\017\n\007subject\030\006 \001(\tB\032" +
      "\n\030io.fathom.cloud.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_fathomcloud_protobuf_SecretRecordItemData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_fathomcloud_protobuf_SecretRecordItemData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_fathomcloud_protobuf_SecretRecordItemData_descriptor,
              new java.lang.String[] { "Key", "Ciphertext", },
              io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.class,
              io.fathom.cloud.protobuf.SecretsModel.SecretRecordItemData.Builder.class);
          internal_static_fathomcloud_protobuf_SecretRecordData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_fathomcloud_protobuf_SecretRecordData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_fathomcloud_protobuf_SecretRecordData_descriptor,
              new java.lang.String[] { "Id", "Item", "Name", "Algorithm", "KeySize", "Subject", },
              io.fathom.cloud.protobuf.SecretsModel.SecretRecordData.class,
              io.fathom.cloud.protobuf.SecretsModel.SecretRecordData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.fathom.cloud.protobuf.CloudCommons.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
