package io.fathom.cloud.compute.api.os.model;

import javax.xml.bind.annotation.XmlElement;

public class Keypair {
    // "fingerprint": "15:b0:f8:b3:f9:48:63:71:cf:7b:5b:38:6d:44:2d:4a",
    // "name": "keypair-601a2305-4f25-41ed-89c6-2a966fc8027a",
    // "public_key":
    // "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC+Eo/RZRngaGTkFs7I62ZjsIlO79KklKbMXi8F+KITD4bVQHHn+kV+4gRgkgCRbdoDqoGfpaDFs877DYX9n4z6FrAIZ4PES8TNKhatifpn9NdQYWA+IkU8CuvlEKGuFpKRi/k7JLos/gHi2hy7QUwgtRvcefvD/vgQZOVw/mGR9Q== Generated by Nova\n"

    public String fingerprint;
    public String name;

    @XmlElement(name = "public_key")
    public String publicKey;

    @XmlElement(name = "private_key")
    public String privateKey;

    // @XmlElement(name = "user_id")
    // public String userId;
}
