#!/bin/bash
### BEGIN INIT INFO
# Provides:       fathomcloud-get-sshkey
# Required-Start: $network
# Required-Stop:  
# Should-Start:   
# Should-Stop:    
# Default-Start:  2 3 4 5
# Default-Stop:   
# Description:    Retrieve the ssh credentials and add to authorized_keys
### END INIT INFO

if [ ! -d /root/.ssh ]; then
  mkdir -p /root/.ssh
  chown root:root /root/.ssh/
  chmod 700 /root/.ssh/
fi

ATTEMPTS=3
FAILED=0

# Fetch public key using Metadata service
# We use the FathomCloud IP, not the EC2 IP
while [ ! -f /root/.ssh/authorized_keys ]; do
    echo "Fetching the SSH authorized key from metadata service"
    wget -q -O - http://[fd00::feed]:8080/latest/meta-data/public-keys/0/openssh-key --connect-timeout=3 --read-timeout=3 --tries=1 > /tmp/ssh-key 2>/dev/null
    if [ $? -eq 0 ]; then
        cat /tmp/ssh-key >> /root/.ssh/authorized_keys
        chmod 0600 /root/.ssh/authorized_keys
        rm -f /tmp/ssh-key
        echo "Successfully retrieved SSH public key"
    else
        FAILED=$(($FAILED + 1))
        if [ $FAILED -ge $ATTEMPTS ]; then
            echo "Failed to retrieve SSH public key after $FAILED attempts, quitting"
            break
        fi
        echo "Could not retrieve SSH public key (attempt #$FAILED/$ATTEMPTS), retrying..."
        sleep 1
    fi
done

exit 0
